api:
  key: ''
  endpoint: 'http://192.168.80.186:6996/api/v1'
model:
  id: '6094bc7c1de4cede4129cc79'

config:
  base_version: '2.0.0'
logging:
  sync_time_interval_s: 10.0
system:
  log_level: 'DEBUG'